### ISSUE TITLE
Add a PatchTemplateBuilder

### ISSUE THREAD

**Issue by Kashomon** [GoogleCloudPlatform/k8s-cluster-bundle#141]
As we have a ComponentBuilder and BundleBuilder, it would be useful to have PatchTemplateBuilder. This would create partial or fully realized patches as part of the build process.

Here's a worked example of what I'm talking about:

```
  apiVersion: bundleext.gke.io/v1alpha1
  kind: PatchTemplateBuilder
  template: |
    apiVersion: v1
    kind: Pod
    spec:
      containers:
        - name: foo-container
          image: '{{.Registry}}/{{.Repository}}/{{.Image}}:{{.Tag}}'

  buildSchema
    # Properties that are not filled out during build-time
    Registry:
      default: '{{.Registry}}'
    Repository:
      default: '{{.Repository}}'

    # Properties that must be supplied during build
    Image:
      type: string
    Tag:
      type: string

  targetSchema:
    # Properties that must be filled out during runtime
    Registry:
      type: string
    Repository:
      type: string
```
