### ISSUE TITLE
componentsuite test fails with nil ref error trying to parse relative paths

### ISSUE THREAD

**Issue by AlexBulankou** [GoogleCloudPlatform/k8s-cluster-bundle#274]
When trying to test component builder with relative paths, 
```yaml
apiVersion: bundle.gke.io/v1alpha1
kind: ComponentBuilder
componentName: my-component
version: 0.0.1
appVersion: 0.0.1
objectFiles:
- url: dir/file.yaml
```

Inliner.objectFiles() fails [here](https://github.com/GoogleCloudPlatform/k8s-cluster-bundle/blob/master/pkg/build/inline.go#L204), then
nil ref is that error is ignored [here](https://github.com/GoogleCloudPlatform/k8s-cluster-bundle/blob/master/pkg/testutil/componentsuite/componentsuite.go#L76):
```
comp, err = inliner.ComponentFiles(ctx, bw.ComponentBuilder(), ts.ComponentFile)
		if err != nil {
		}
```
CC @Kashomon
